# -*- coding: utf-8 -*-
"""Proyecto final programación 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JBrQfXh-bN0B9Lb8EzKiHI8thvfG_DVa
"""

#Entrega final programación
#Comparación entre los resultados del ICFES 2020 para Calendario A y Calendario B
#Integrantes: Tomás Lopez Chaparro, Sofía Pallares Cristancho, María Catalina Santamaría Moreno

import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder,StandardScaler
sns.set(style="whitegrid", palette="pastel")
from sklearn.decomposition import PCA

id = ["a8xr-en99", "rnvb-vnyh"]   #Cada ID representa resultados de los periodos 2020-1 y 2020-2 respectivamente
dfs = {}  #Diccionario vacío para guardar cada df
i=0
for i, codigo in enumerate(id):
    url = f"https://www.datos.gov.co/resource/{codigo}.json?$limit=50000" #Hace una url distinta para cada id con un máximo de 500000 respuestas
    r = requests.get(url) #Pedir permisos en cada url con los distintos id
    data = r.json()
    df = pd.DataFrame(data) #Convertimos los datos en formato json a un df
    nombre = f"df{i+1}" #Le pone un nombre distinto a cada df que creamos
    dfs[nombre] = df #Guardar cada df en el diccionario dfs

df1 = dfs.get("df1", pd.DataFrame())   # si no existe, devuelve DataFrame vacío
df2 = dfs.get("df2", pd.DataFrame())
print("Cantidad de estudiantes para el 2020-1:", len(df1))
print("Cantidad de estudiantes para el 2020-2:", len(df2)) #Se muestra la cantidad de filas en cada df (cada fila es un estudiante)

df1 = dfs["df1"].head(15000)
df2 = dfs["df2"].head(15000)

print("Nueva cantidad de estudiantes para el 2020-1:", len(df1))
print("Nueva cantidad de estudiantes para el 2020-2:", len(df2)) #Se muestra la cantidad de filas en cada df (cada fila es un estudiante)

print("\nColumnas del 2020-1:")
print(df1.columns) #Se muestra las columnas en el df1 (cada columna es una pregunta diferente)

print("\nColumnas del 2020-2:")
print(df2.columns) #Se muestra las columnas en el df2 (cada columna es una pregunta diferente)

if list(df1.columns) == list(df2.columns):
  print("Ambos periodos tiene las mismas columnas")
else:
  print("Los periodos tienen columnas distintas") #Se uso un if para saber si la lista de columnas en ambos periodos era igual

columnas_comunes = [] #Lista vacía para guardar las columnas iguales
for columna in df1.columns:
    if columna in df2.columns:
        columnas_comunes.append(columna) #Si la columna esta en ambos df se guarda en la lista
print(f"La cantidad de preguntas iguales es {len(columnas_comunes)} y estas son:\n{columnas_comunes}")

df1f = df1[columnas_comunes].copy()
df2f = df2[columnas_comunes].copy() #Se crean 2 nuevos df en los que solo estan las preguntas que tienen ambos periodos

df1f.head()

#Renombrar las columnas que nos interesan
asignaturas = {"punt_matematicas": "matematicas","punt_ingles": "ingles","punt_c_naturales": "naturales","punt_lectura_critica": "lectura","punt_sociales_ciudadanas": "sociales"}
#Cambiar estos nombres en ambos df
df1f.rename(columns=asignaturas, inplace=True)
df2f.rename(columns=asignaturas, inplace=True)

#Pedir al usuario el nombre de la asignatura a comparar
asignatura = input("Escribe la asignatura que quieres comparar: ").strip().lower()
#Verificar si la asignatura escrita existe en ambos df y en caso de si hacerlo guardarla, en caso de no avisar
if asignatura in df1f.columns and asignatura in df2f.columns:
    col = asignatura
else:
    print("Esa asignatura no es válida")

#Convertir ambas columnas a númericas
df1f[col] = pd.to_numeric(df1f[col], errors='coerce')
df2f[col] = pd.to_numeric(df2f[col], errors='coerce')

class Comparador:  #Se define una clase para analizar y comparar datos entre dos periodos.
    def __init__(self, df1, df2, asignatura):
        self.df1 = df1  #Guarda el primer df como atributo del objeto.
        self.df2 = df2  #Guarda el segundo df como atributo del objeto.
        self.asignatura = asignatura  #Guarda la asignatura seleccionada como atributo del objeto.

    #Estadísticas descriptivas para cada una de las variables en ambos periodos
    def estadisticas(self):
        # Método que muestra las estadísticas básicas de la asignatura seleccionada para los dos periodos.
        print("\nEstadísticas (2020-1):")
        display(self.df1[self.asignatura].describe().round(2))  #Calcula las estadísticas descriptivas de la columna seleccionada en 2020-1 y redondea los resultados a 2 decimales
        print("\nEstadísticas (2020-2):")
        display(self.df2[self.asignatura].describe().round(2))  #Calcula las estadísticas descriptivas de la misma columna seleccionada en 2020-2 y redondea los resultados a 2 decimales

comparador = Comparador(df1f, df2f, col)
# Crea un objeto (instancia) de la clase Comparador llamado comparador

comparador.estadisticas()
# Llama al método estadisticas del objeto comparador

# Asegura que la columna seleccionada tenga valores numéricos
df1f[col] = pd.to_numeric(df1f[col], errors='coerce')
df2f[col] = pd.to_numeric(df2f[col], errors='coerce')

media1 = df1f[col].mean()  #Calcula la media (promedio) de la columna seleccionada (col) en el periodo 2020-1 (df1f).
media2 = df2f[col].mean()  #Calcula la media (promedio) de la misma columna (col) pero en el periodo 2020-2 (df2f).

#Muestra en pantalla el valor de la media de ambos periodos, redondeada a 2 decimales
print(f"\nMedia 2020-1: {media1:.2f}")
print(f"Media 2020-2: {media2:.2f}")

#Verifica que ambas medias sean valores numéricos válidos (no NaN) y compara cual es mayor
if pd.notna(media1) and pd.notna(media2):
    if media1 > media2:
        print(f"En promedio, el Calendario B (2020-1) obtuvo mejores resultados en {col}.")
    elif media2 > media1:
        print(f"En promedio, el Calendario A (2020-2) obtuvo mejores resultados en {col}.")
    else:
        print("Ambos calendarios tienen el mismo promedio.")

class Comparador:
    def __init__(self, df1, df2, asignatura):
        self.df1 = df1
        self.df2 = df2
        self.asignatura = asignatura

    def graficas(self):
        col = self.asignatura

        #Histograma
        plt.figure(figsize=(8,5))
        #Dibuja un histograma para los datos de ambos periodos, define el color de cada uno, kde=True sirve para agregar una curva de densidad suavizada sobre el histograma, bins=30 divide los valores en 30 intervalos o barras y alpha=0.5 define la transparencia
        sns.histplot(self.df1[col], color='#FFB347', label='2020-1', kde=True, bins=30, alpha=0.5)
        sns.histplot(self.df2[col], color='#89CFF0', label='2020-2', kde=True, bins=30, alpha=0.5)
        plt.title(f"Distribución de puntajes en {col.capitalize()}") #Agrega un título al gráfico con el nombre de la asignatura capitalizado
        plt.xlabel("Puntaje") #Añade la etiqueta del eje X (horizontal)
        plt.ylabel("Frecuencia") #Añade la etiqueta del eje Y (vertical)
        plt.legend() #Muestra la leyenda con las etiquetas para identificar cada color
        plt.show() #Muestra la gráfica

        #Densidad de puntajes (KDE)
        plt.figure(figsize=(8,5))
        #Dibuja curvas de densidad para los datos de ambos periodos, permitiendo comparar cómo se distribuyen los puntajes de manera suavizada
        sns.kdeplot(self.df1[col], color='#FFB347', label='2020-1', fill=True, alpha=0.3)
        sns.kdeplot(self.df2[col], color='#89CFF0', label='2020-2', fill=True, alpha=0.3)
        plt.title(f"Densidad de puntajes en {col.capitalize()}") #Agrega un título al gráfico con el nombre de la asignatura
        plt.xlabel("Puntaje") #Etiqueta el eje X indicando los puntajes
        plt.ylabel("Densidad") #Etiqueta el eje Y indicando la densidad o concentración de valores
        plt.legend() #Muestra las etiquetas que diferencian cada periodo
        plt.show() #Muestra la gráfica

        #Tendencia suavizada
        plt.figure(figsize=(8,5))
        #Dibuja líneas que representan la tendencia de los puntajes ordenados de menor a mayor para ambos periodos, aplicando una media móvil que suaviza las variaciones
        sns.lineplot(x=range(len(self.df1[col].sort_values())), y=self.df1[col].sort_values().rolling(300).mean(), color='#FFB347', label='2020-1')
        sns.lineplot(x=range(len(self.df2[col].sort_values())), y=self.df2[col].sort_values().rolling(300).mean(), color='#89CFF0', label='2020-2')
        plt.title(f"Tendencia suavizada de puntajes en {col.capitalize()}") #Agrega un título que indica la tendencia de los puntajes en la asignatura seleccionada
        plt.xlabel("Estudiantes (ordenados por puntaje)") #Etiqueta el eje X indicando que los valores están ordenados por puntaje
        plt.ylabel("Puntaje promedio móvil") #Etiqueta el eje Y mostrando que se trata del promedio móvil de los puntajes
        plt.legend() #Muestra las etiquetas que diferencian cada periodo
        plt.show() #Muestra la gráfica

        #Gráfico de barras
        plt.figure(figsize=(6,5))
        #Crea un gráfico de barras que compara las medias de los puntajes entre los dos periodos usando colores diferentes para cada uno
        medias = [self.df1[col].mean(), self.df2[col].mean()]
        sns.barplot(x=['2020-1','2020-2'], y=medias, palette=['#FFB347', '#89CFF0'])
        plt.title(f"Promedio de puntajes en {col.capitalize()}") #Agrega un título indicando que se muestran los promedios por periodo
        plt.ylabel("Puntaje promedio") #Etiqueta el eje Y indicando que representa el valor promedio del puntaje
        for i, v in enumerate(medias):
            plt.text(i, v + 0.5, f"{v:.1f}", ha='center', fontweight='bold') #Muestra el valor numérico de cada barra encima de ella con dos decimales
        plt.show() #Muestra la gráfica

def graficas(self):
    col = self.asignatura #Guarda el nombre de la asignatura seleccionada

    #Asegura que las columnas sean numéricas
    self.df1[col] = pd.to_numeric(self.df1[col], errors='coerce') #Convierte los datos del primer periodo a valores numéricos, los que no pueda convertir los reemplaza por NaN
    self.df2[col] = pd.to_numeric(self.df2[col], errors='coerce') #Convierte los datos del segundo periodo a valores numéricos, los que no pueda convertir los reemplaza por NaN

    #Histograma
    plt.figure(figsize=(8,5)) #Crea una figura con tamaño de 8x5 pulgadas
    sns.histplot(self.df1[col], color='#FFB347', label='2020-1', kde=True, bins=30, alpha=0.5) #Dibuja un histograma con los datos del primer periodo (color naranja)
    sns.histplot(self.df2[col], color='#89CFF0', label='2020-2', kde=True, bins=30, alpha=0.5) #Dibuja un histograma con los datos del segundo periodo (color azul)
    plt.title(f"Distribución de puntajes en {col.capitalize()}") #Agrega un título al gráfico con el nombre de la asignatura
    plt.xlabel("Puntaje") #Etiqueta el eje X indicando los valores de puntaje
    plt.ylabel("Frecuencia") #Etiqueta el eje Y indicando la cantidad de observaciones por intervalo
    plt.legend() #Muestra la leyenda para identificar cada periodo
    plt.show() #Muestra la gráfica

    #Densidad de puntajes (KDE)
    plt.figure(figsize=(8,5)) #Crea una nueva figura para la densidad
    sns.kdeplot(self.df1[col], color='#FFB347', label='2020-1', fill=True, alpha=0.3) #Dibuja una curva de densidad para los datos del primer periodo
    sns.kdeplot(self.df2[col], color='#89CFF0', label='2020-2', fill=True, alpha=0.3) #Dibuja una curva de densidad para los datos del segundo periodo
    plt.title(f"Densidad de puntajes en {col.capitalize()}") #Agrega un título al gráfico con el nombre de la asignatura
    plt.xlabel("Puntaje") #Etiqueta el eje X indicando los puntajes
    plt.ylabel("Densidad") #Etiqueta el eje Y indicando la densidad de los valores
    plt.legend() #Muestra la leyenda con las etiquetas de cada periodo
    plt.show() #Muestra la gráfica

    #Tendencia suavizada
    plt.figure(figsize=(8,5)) #Crea una figura para la tendencia
    sns.lineplot(x=range(len(self.df1[col].sort_values())), y=self.df1[col].sort_values().rolling(300).mean(), color='#FFB347', label='2020-1') #Dibuja la tendencia suavizada de los puntajes del primer periodo usando una media móvil de 300 observaciones
    sns.lineplot(x=range(len(self.df2[col].sort_values())), y=self.df2[col].sort_values().rolling(300).mean(), color='#89CFF0', label='2020-2') #Dibuja la tendencia suavizada para el segundo periodo
    plt.title(f"Tendencia suavizada de puntajes en {col.capitalize()}") #Agrega un título que indica la tendencia de los puntajes
    plt.xlabel("Estudiantes (ordenados por puntaje)") #Etiqueta el eje X mostrando que los estudiantes están ordenados por puntaje
    plt.ylabel("Puntaje promedio móvil") #Etiqueta el eje Y indicando que se muestra un promedio móvil de los puntajes
    plt.legend() #Muestra la leyenda con los nombres de los periodos
    plt.show() #Muestra la gráfica

    #Gráfico de barras
    plt.figure(figsize=(6,5)) #Crea una figura para el gráfico de barras
    medias = [self.df1[col].mean(), self.df2[col].mean()] #Calcula la media de los puntajes para cada periodo
    sns.barplot(x=['2020-1','2020-2'], y=medias, palette=['#FFB347', '#89CFF0']) #Crea un gráfico de barras comparando las medias entre los dos periodos
    plt.title(f"Promedio de puntajes en {col.capitalize()}") #Agrega un título indicando que se comparan los promedios
    plt.ylabel("Puntaje promedio") #Etiqueta el eje Y como puntaje promedio
    for i, v in enumerate(medias): #Recorre las medias para añadir los valores encima de las barras
        plt.text(i, v + 0.5, f"{v:.1f}", ha='center', fontweight='bold') #Escribe el valor numérico encima de cada barra
    plt.show() #Muestra la gráfica

from types import MethodType
Comparador.graficas = graficas

asignaturas = ["matematicas", "lectura_critica", "ingles", "ciencias_naturales", "sociales"]
comparador = Comparador(df1f, df2f, col)
comparador.graficas()

data =df1f #traer datos de 2020-1
# Preprocesamiento: codificar variables categóricas
for col in data.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col].astype(str))

# Separar características y target
X = data.drop(columns=['punt_global'])
y = data['punt_global']

# Escalar características antes de PCA
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Aplicar PCA para reducción dimensional a 10 componentes principales
pca = PCA(n_components=10)
X_pca = pca.fit_transform(X_scaled)

# Dividir datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.3, random_state=42)

# Crear y entrenar modelo Random Forest con datos reducidos
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

# Hacer predicciones
y_pred = model.predict(X_test)

# Evaluar desempeño
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Error absoluto medio (MAE): {mae:.2f}')
print(f'Coeficiente de determinación (R^2): {r2:.2f}')


plt.figure(figsize=(10, 6))
plt.scatter(range(len(y_test)), y_test, color='blue', label='Valores reales')
plt.scatter(range(len(y_pred)), y_pred, color='red', alpha=0.6, label='Predicciones')
plt.title('Comparación de valores reales y predicciones')
plt.xlabel('Instancias')
plt.ylabel('Puntaje global')
plt.legend()
plt.show()


plt.figure(figsize=(12, 6))
plt.plot(range(len(y_test)), y_test, label='Valores reales', marker='o')
plt.plot(range(len(y_pred)), y_pred, label='Predicciones', marker='x')
plt.title('Comparación de valores reales vs Predicciones - Gráfico de líneas')
plt.xlabel('Instancias')
plt.ylabel('Puntaje global')
plt.legend()
plt.grid(True)
plt.show()

data = df2f  # traer datos de 2020-2

# Preprocesamiento: codificar variables categóricas
for col in data.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col].astype(str))

# Separar características y target
X = data.drop(columns=['punt_global'])
y = data['punt_global']

# Escalar características antes de PCA
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Aplicar PCA para reducción dimensional a 10 componentes principales
pca = PCA(n_components=10)
X_pca = pca.fit_transform(X_scaled)

# Dividir datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.3, random_state=42)

# Crear y entrenar modelo Random Forest con datos reducidos
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

# Hacer predicciones
y_pred = model.predict(X_test)

# Evaluar desempeño
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Error absoluto medio (MAE): {mae:.2f}')
print(f'Coeficiente de determinación (R^2): {r2:.2f}')

# Gráficas
plt.figure(figsize=(10, 6))
plt.scatter(range(len(y_test)), y_test, color='blue', label='Valores reales')
plt.scatter(range(len(y_pred)), y_pred, color='red', alpha=0.6, label='Predicciones')
plt.title('Comparación de valores reales y predicciones')
plt.xlabel('Instancias')
plt.ylabel('Puntaje global')
plt.legend()
plt.show()

plt.figure(figsize=(12, 6))
plt.plot(range(len(y_test)), y_test, label='Valores reales', marker='o')
plt.plot(range(len(y_pred)), y_pred, label='Predicciones', marker='x')
plt.title('Comparación de valores reales vs Predicciones - Gráfico de líneas')
plt.xlabel('Instancias')
plt.ylabel('Puntaje global')
plt.legend()
plt.grid(True)
plt.show()